/// Predefined icon names for custom categories (no image uploads).
const List<String> kCustomCategoryIconNames = [
  'sun',
  'moon',
  'heart',
  'star',
  'cloud',
  'book',
  'chat',
  'spark',
  'tree',
  'dream',
  'childhood',
  'relationship',
  'lightning',
  'flower',
  'compass',
  'butterfly',
  'music_note',
  'mountain',
  'waves',
  'key',
  'crown',
  'palette',
  'anchor',
  'gift',
  'candle',
  'cup',
  'book_open',
  'infinity',
  'eye',
  'lotus',
  'bridge',
  'embrace',
  'journal',
  'mirror',
];

const String kDefaultCustomCategoryIcon = 'sun';
